# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl:
safe: true

title:		Dave
tagline:	'blog'
description:	'My personal blog.'
url:		https://www.vernizzis.it
commentsystem:	__google
disqus:		example

author:
  name:		'Davide Vernizzi'
  url:		https://www.twitter.com/davide_vernizzi

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/davide_vernizzi
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/davidevernizzi
    desc:	Fork me on github

menu:
  - title:	Home
    url:	/

  - title:	Docman
    url:	/docman

  - title:	Gluglu
    url:	http://gluglu.vernizzis.it/

  - title:	About
    url:	/about

copyright:
  author:	Dave
  url:		https://www.vernizzis.it
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-57961528-1
