# Dependencies
#markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl:
safe: true

title:		Dave
tagline:	'blog'
description:	'My personal blog.'
url:		http://www.vernizzis.it
commentsystem:	__google
disqus:		example

author:
  name:		'Davide Vernizzi'
  url:		https://www.twitter.com/davide_vernizzi

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/bb.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/davide_vernizzi
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/davidevernizzi
    desc:	Fork me on github

menu:
  - title:	Home
    url:	/

  - title:	Docman
    url:	/docman

  - title:	About
    url:	/about

copyright:
  author:	Dave
  url:		https://www.vernizzis.it
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-57961528-1

jekyll-crosspost_to_medium:
  enabled: true #| false
  cache: .jekyll-crosspost_to_medium
  status: draft #public (default) | draft | unlisted
  license: cc-40-by-sa #all-rights-reserved (default) | cc-40-by | cc-40-by-sa | cc-40-by-nd | cc-40-by-nc | cc-40-by-nc-nd | cc-40-by-nc-sa | cc-40-zero | public-domain
  text: '<p><i>Dave</i></p>',
  backdate: true # (default) | false
