name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: |
        docker run \
        -e ALGOLIA_API_KEY=$ALGOLIA_API_KEY \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll algolia"
